// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE

import * as ReactDom from "react-dom";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Greeting$ReasonOnRails from "./Greeting.bs.js";

function embed(target) {
  ReactDom.render(ReasonReact.element(undefined, undefined, Greeting$ReasonOnRails.make("Reason", /* array */[])), target);
  return /* () */0;
}

export {
  embed ,
  
}
/* react-dom Not a pure module */
